### ISSUE TITLE
Permitir que a inicialización de logs cun nivel inexistente deshabilite o sistema

### ISSUE THREAD

**Issue by alambike** [prefapp/catro_eixos_js#10]
En vez de petar, que  deshabilite o sistema de logs.

Ou que pete pero que se poida setear algún nivel documentado que deshabilite o log (en plan ``` logs:{ nivel: off}```)

**Comment by frmadem** [comment]
Fixed en [commit](https://github.com/prefapp/catro_eixos_js/commit/c4c0e9c404a4d151a31cb85b30baed60b5eab638)

Si no se pone nivel alguno o se pone **off* los logs se deshabilitan. 

En caso de poner un nivel no definido se lanza excepción.
