### ISSUE TITLE
Error en repl

### ISSUE THREAD

**Issue by alambike** [prefapp/catro_eixos_js#14]
Desde algunhas das últimas actualización a consola non e capaz de executar un proceso de tipo Api:

```
>.r Hello.hello_get
{
   "id": "tarea0",
   "args": {
      "proceso": "Hello.hello_get"
   },
   "resultados": {
      "estado": "KO",
      "error": "INSTANCIACION_DE_PROCESO:TypeError: Cannot read property 'getInstancia' of undefined"
   }
```

**Comment by frmadem** [comment]
Eso ocurre en la versión previa a (v2.8.5) el problema es que, cuando un procesoSwagger no tenía un producto asociado, reventaba la instanciación del mismo desde CatroEixosMiddleware, ahora está solucionado.
