### ISSUE TITLE
Setear automáticamente a 100 o porcentaje_completado, ao finalizar o proceso

### ISSUE THREAD

**Issue by alambike** [prefapp/catro_eixos_js#17]
Ata ahora a responsabilidade de poñer a 100% o porcentaje_completado, recae no proceso, polo que pode finalizarse sen chegar a este 100

**Comment by frmadem** [comment]
Sin problema, se podría poner el proceso al 100% una vez que terminase, sea cual sea el estado de terminación. ADemás, y dado que eso se refleja en el job, descargaríamos de responsabilidad al proceso de hacer ese trabajo.

**Comment by alambike** [comment]
Pero xa se está facendo, o problema ven porque non se setea  os resultados:
```JOB { id: '0d269813-eaec-4c27-85c7-ec9115d9c8d6',
  estado: 'FINISHED',
  porcentaje_completado: 100,
  finalizado: 'OK',
  error: '',
  resultados: 
   { hito: 'LIMPIAR_CACHE_PRODUCCION',
     porcentaje_completado: 90,
     report_DASH: { pelicano: 1 },
     report_HLS: { pelicano: 1 } } }
```

**Comment by frmadem** [comment]
Claro, porque era el job el que se estaba cerrando automáticamente, no el porcentaje del proceso. Ahora, con este [parche](8baadf2e5be11a5f0f8ae2915cf27ef59b0ae447) eso no ocurre. Con lo cual, ya no se necesitaría cerrar el porcentaje del job en catro-eixos-jobs porque ya se haría desde el propio proceso en catro-eixos-js
