### ISSUE TITLE
Controlar error en metodos OK/KO

### ISSUE THREAD

**Issue by alambike** [prefapp/catro_eixos_js#2]
Al producirse un error dentro de un método OK|KO|EVAL, relativo a un metodo del proceso, no tenemos detalles del error

**Comment by frmadem** [comment]
Resuelto en rama https://github.com/prefapp/catro_eixos_js/tree/nuevo_ejecutor

**Comment by alambike** [comment]
Pero esta en master xa @frmadem ?
