### ISSUE TITLE
Disponer de un método genérico para cualquier método validar

### ISSUE THREAD

**Issue by alambike** [prefapp/catro_eixos_js#3]
Por defecto, si no se ha definido el KO__vXX, que se loguee el error de "Validacion __vXX fallida"

**Comment by frmadem** [comment]
Resulto en rama https://github.com/prefapp/catro_eixos_js/tree/nuevo_ejecutor

**Comment by alambike** [comment]
Penso que non deberías pechala mentras non este en master no?
