### ISSUE TITLE
En los procesos, validar que existan los metodos referidos en __v() y __r()

### ISSUE THREAD

**Issue by alambike** [prefapp/catro_eixos_js#6]
Si no existe alguno de los metodos referenciados en __v() o __r() debería lanzar una excepción la ejecución del proceso

**Comment by frmadem** [comment]
Fixed en [commit](https://github.com/prefapp/catro_eixos_js/commit/19c140a35586f9d887aaaaa92a6169b4aff2686e) tanto para __v como para __r
